spring.application.name=EmailMicroService

#mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bootspring86@gmail.com
spring.mail.password=vrst qmhh tqpf tzxt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.port=8081
